{% set name = "des-pizza-patches" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/esheldon/pizza-patches/archive/refs/tags/{{ version }}.tar.gz
  sha256: af069c2cc3574f61f605393be70efbee8dcad7731ee389f623128a8187defaf1

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - treecorr
    - fitsio
    - tqdm
    - esutil
    - mattspy
    - des-y6utils
    - healsparse
    - matplotlib-base
    - skyproj
    - jq
    - h5py

test:
  imports:
    - pizza_patches

about:
  home: https://github.com/esheldon/pizza-patches
  summary: 'Create patches for pizza slices and generate patch files'
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - beckermr
